name: Todo Frontend
on:
  push:
    branches:
    - main
    paths:
    - todo-frontend/src/**
    - todo-frontend/pom.xml
    - todo-frontend/ui/**
    - .github/workflows/*
  pull_request:
    branches:
    - main
    paths:
    - todo-frontend/src/**
    - todo-frontend/pom.xml
    - todo-frontend/ui/**
    - .github/workflows/*
jobs:
  unit-test:
    uses: making/oauth2-sso-demo/.github/workflows/unit-test.yaml@main
    with:
      pom_dir: todo-frontend
  build-oci-image-jvm-amd64:
    needs: unit-test
    uses: making/oauth2-sso-demo/.github/workflows/build-oci-image-jvm.yaml@main
    with:
      pom_dir: todo-frontend
      image_name: todo-frontend_jvm_amd64
      image_file: todo-frontend_jvm_amd64.yaml
      image_platform: linux/amd64
  build-oci-image-jvm-aarch64:
    needs: unit-test
    uses: making/oauth2-sso-demo/.github/workflows/build-oci-image-jvm.yaml@main
    with:
      pom_dir: todo-frontend
      image_name: todo-frontend_jvm_aarch64
      image_file: todo-frontend_jvm_aarch64.yaml
      image_platform: linux/arm64
      use_qemu: true
  push-multi-arch-image-jvm:
    needs:
    - build-oci-image-jvm-amd64
    - build-oci-image-jvm-aarch64
    uses: making/oauth2-sso-demo/.github/workflows/push-multi-arch-image.yaml@main
    with:
      prefix: jvm
      pom_dir: todo-frontend
  save-image-jvm-amd64:
    needs: build-oci-image-jvm-amd64
    uses: making/workflows/.github/workflows/save-images.yaml@main
    with:
      image_name: todo-frontend_jvm_amd64
      image_file: todo-frontend_jvm_amd64.yaml
  save-image-jvm-aarch64:
    needs: build-oci-image-jvm-aarch64
    uses: making/workflows/.github/workflows/save-images.yaml@main
    with:
      image_name: todo-frontend_jvm_aarch64
      image_file: todo-frontend_jvm_aarch64.yaml