name: Unit Test
on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: graalvm
        cache: 'maven'
    - name: unit test
      run: ./mvnw -V -f ${{ inputs.module }} clean test --no-transfer-progress