name: Unit Test
on:
  workflow_call:
    inputs:
      pom_dir:
        required: false
        type: string
        default: '.'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: graalvm
        cache: 'maven'
    - name: unit test
      run: ./mvnw -V -f ${{ inputs.pom_dir }} clean test --no-transfer-progress